### ISSUE TITLE
Picking

### ISSUE THREAD

**Issue by taumuon** [gecko0307/dmech#10]
Hi,

I've been using dmech a very simple game demo/prototype. I'm impressed how much work is in these libraries - is this the work of one person?

Anyway, I ran into some issues with picking, so I created a cut-down application to investigate. In my application I was trying to use PhysicsWorld.raycast, but it seemed to return a body other than the one I was picking (I was using a local build from the master of dmech, and I'd modified PhysicsWorld.raycast to set the shape - as I had a rigid body with many shapes attached and wanted to see which one of them was picked).

I created a cut-down application to investigate picking - I created a 'plane' of cubes, arranged in the x-z plane, and put a camera over the center cube along the y axis looking onto the plane, and cast a ray to each cube's centre to test that picking worked.

I first created a demo in bullet for comparison: https://gist.github.com/taumuon/7948d557da1f5779ca98643a433c6e48
My dmech demo is at: https://gist.github.com/taumuon/a25ad4206d5e18add98381dc024a9ef5

I got the dmech demo giving the same results as the c++ bullet demo by picking testing against body directly, as in the dmech pyramid demo.
Trying to pick using PhysicsWorld.raycast doesn't work.

I had another question (which is probably more of a d language question rather than dmech), but if I change the line:
Vector3f origin = Vector3f(0, 10, 0);
to 
Vector3f origin = new Vector3f(0, 10, 0);
then I get the wrong box picked (similar to what I'm seeing in my app). I'm curious this doesn't work, but why it compiles - is the vector boxed?

Thanks,

Gary

**Comment by gecko0307** [comment]
Hello! Thank you for your interest! dmech is written fully by me. 
I never experienced problems with `PhysicsWorld.raycast`. I'll test your demo and see what's going wrong.

As for vectors, instantiating with `new` doesn't work for me. It says: `Error: invalid cast from 'Vector!(float, 3)*' to 'float'`. I don't use DMD though, I test everything locally with LDC.

**Comment by gecko0307** [comment]
It seems that you're using wrong ray vectors. The first should be world-space ray origin, and the second should be normalized origin-space ray direction. I drew a quick scheme to illustrate:

![dmech-ray](https://user-images.githubusercontent.com/1396859/36472757-c7580ff4-1703-11e8-8946-0a55f851fe69.png)

Correct raycast query in your case would look as follows:
```d
world.raycast(Vector3f(x - 5, 10, z - 5), Vector3f(0, -1, 0), 1000, castResult);
``` 
It gives the same result as `pick` function.

I know, this is somewhat counter-intuitive and rather different from how dlib's `Ray` is constructed (with begin/end points), but it is actually convenient when doing continuous casts in one direction, which is what I usually use `raycast` for (causes less normalizations). I can make a separate `Ray` based version of `raycast` for less confusion.

It's also worth saying that casting a ray from inside of a `RigidBody` will likely give unintended result because of collision with that body's own geometry. To avoid this, a body can be made invisible for rays with `raycastable` property. Same option exists for `ShapeComponent` as well. Inactive bodies and shapes are also ignored.

**Comment by taumuon** [comment]
Hi,
Thanks for getting back to me. 
With your help, I got my example working (with a single origin, to simulate pick rays projecting from the camera) with the following:
			CastResult castResult;
			Vector3f target = Vector3f(x - 5, 0, z - 5);
			Vector3f direction = target - origin;
			world.raycast(origin, direction.normalized, 1000, castResult);
			RigidBody rbody = castResult.rbody;
Thanks again,
Gary
